# Generated by Django 3.0.2 on 2020-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('DOU', models.CharField(max_length=100)),
                ('File', models.FileField(upload_to='Attendance')),
            ],
        ),
    ]
