# Generated by Django 3.0.2 on 2020-04-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200429_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atitle', models.CharField(max_length=100)),
                ('Asubject', models.CharField(max_length=100)),
                ('ADOU', models.CharField(max_length=100)),
                ('AFile', models.FileField(upload_to='Assignment')),
            ],
        ),
    ]
