# Generated by Django 3.0.2 on 2020-05-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfID', models.CharField(max_length=15)),
                ('CourseID', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='timetable',
            name='TFile',
            field=models.FileField(upload_to='Timetable'),
        ),
    ]
